/**
 * An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
 * @export
 * @enum {string}
 */
export enum SportType {
    AlpineSki = <any>'AlpineSki',
    BackcountrySki = <any>'BackcountrySki',
    Badminton = <any>'Badminton',
    Canoeing = <any>'Canoeing',
    Crossfit = <any>'Crossfit',
    EBikeRide = <any>'EBikeRide',
    Elliptical = <any>'Elliptical',
    EMountainBikeRide = <any>'EMountainBikeRide',
    Golf = <any>'Golf',
    GravelRide = <any>'GravelRide',
    Handcycle = <any>'Handcycle',
    HighIntensityIntervalTraining = <any>'HighIntensityIntervalTraining',
    Hike = <any>'Hike',
    IceSkate = <any>'IceSkate',
    InlineSkate = <any>'InlineSkate',
    Kayaking = <any>'Kayaking',
    Kitesurf = <any>'Kitesurf',
    MountainBikeRide = <any>'MountainBikeRide',
    NordicSki = <any>'NordicSki',
    Pickleball = <any>'Pickleball',
    Pilates = <any>'Pilates',
    Racquetball = <any>'Racquetball',
    Ride = <any>'Ride',
    RockClimbing = <any>'RockClimbing',
    RollerSki = <any>'RollerSki',
    Rowing = <any>'Rowing',
    Run = <any>'Run',
    Sail = <any>'Sail',
    Skateboard = <any>'Skateboard',
    Snowboard = <any>'Snowboard',
    Snowshoe = <any>'Snowshoe',
    Soccer = <any>'Soccer',
    Squash = <any>'Squash',
    StairStepper = <any>'StairStepper',
    StandUpPaddling = <any>'StandUpPaddling',
    Surfing = <any>'Surfing',
    Swim = <any>'Swim',
    TableTennis = <any>'TableTennis',
    Tennis = <any>'Tennis',
    TrailRun = <any>'TrailRun',
    Velomobile = <any>'Velomobile',
    VirtualRide = <any>'VirtualRide',
    VirtualRow = <any>'VirtualRow',
    VirtualRun = <any>'VirtualRun',
    Walk = <any>'Walk',
    WeightTraining = <any>'WeightTraining',
    Wheelchair = <any>'Wheelchair',
    Windsurf = <any>'Windsurf',
    Workout = <any>'Workout',
    Yoga = <any>'Yoga'
}